---
title: "Modeling Audience Networks 1"
author: "Subhayan Mukerjee"
date: "6/1/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(igraph)
library(ggplot2)
library(tidyverse)
```



## Model 1:

## Simple model with M = 2 media, n individuals

### Build network incrementally. Each individual randomly chooses a media outlet.

```{r}
M <- 2
N <- 20

all_media <- paste0("M", 1:M)
all_people <- paste0("N", 1:N)

set.seed(42)

audience_edgelists <- list()
audience_edgelist <- NULL
for(n in all_people) {
  # each person chooses media at random
  
  # probability of choosing each outlet = 1/N
  media_prob <- rep(1/(length(all_media)), length(all_media)) # 0.5, 0.5
  n_choice <- sample(all_media, 1, replace = TRUE, prob = media_prob)
  
  #network edge between person n and their choice
  n_edge <- c(n, n_choice)
  audience_edgelist <- rbind(audience_edgelist, n_edge)
  
  # message(paste0("n: ", n))
  # print(audience_edgelist)
  audience_edgelists[[n]] <- audience_edgelist
}
```

### Build the audience overlap (i.e. the media projection of the network) at each step

```{r}

media_projection_networks <- list()

for(i in 1:length(all_people)){
  audience_graph <- graph_from_edgelist(audience_edgelists[[i]], directed = FALSE)
  
  # assign type of node
  V(audience_graph)$type <- substr(V(audience_graph)$name, 1, 1) == "M"
  
  # color node based on type
  V(audience_graph)$color <- ifelse(V(audience_graph)$type, "tomato", "gold")
  
  # change shape of node based on type
  V(audience_graph)$shape <- ifelse(V(audience_graph)$type, "square", "circle") 
  
  # edge color
  E(audience_graph)$edge.color <- "gray80"
  
  # get the audience projection
  media_projection <- bipartite_projection(audience_graph)[[1]]
  
  # store in the list
  media_projection_networks[[i]] <- media_projection
  
  # plot
  # message(i)
  # plot(media_projection)
}
```

### Parameterize the above code chunks

```{r}

build_audience_edgelists <- function(M = 2, N) {
  all_media <- paste0("M", 1:M)
  all_people <- paste0("N", 1:N)
  
  audience_edgelists <- list()
  audience_edgelist <- NULL
  for(n in all_people) {
    # each person chooses media at random
    # probability of choosing each outlet = 1/N
    # media_prob <- rep(1/(length(all_media)), length(all_media))
    media_prob <- c(0.5, 0.5)
    n_choice <- sample(all_media, 1, replace = TRUE, prob = media_prob)
    
    #network edge between person n and their choice
    n_edge <- c(n, n_choice)
    audience_edgelist <- rbind(audience_edgelist, n_edge)
    
    audience_edgelists[[n]] <- audience_edgelist
  }
  
  return(audience_edgelists)
}

get_incremental_media_projections <- function(audience_edgelists) {
  
  all_people <- length(audience_edgelists)
  # message(all_people)
  media_projection_networks <- list()
  for(i in 1:all_people){
    audience_graph <- graph_from_edgelist(audience_edgelists[[i]], directed = FALSE)
    
    # assign type of node
    V(audience_graph)$type <- substr(V(audience_graph)$name, 1, 1) == "M"
    
    # color node based on type
    V(audience_graph)$color <- ifelse(V(audience_graph)$type, "tomato", "gold")
    
    # change shape of node based on type
    V(audience_graph)$shape <- ifelse(V(audience_graph)$type, "square", "circle") 
    
    # edge color
    E(audience_graph)$edge.color <- "gray80"
    
    # get the audience projection
    media_projection <- bipartite_projection(audience_graph)[[1]]
    
    # store in the list
    media_projection_networks[[i]] <- media_projection
    
    # plot
    # message(i)
    # plot(media_projection)
  }
  
  return(media_projection_networks)
  
}

```


### run the simulation

```{r}
set.seed(42)

m <- 2
n <- 10
NS <- 100

sim_res <- NULL
for(i in 1:NS) {
  au_el <- build_audience_edgelists(N = n)
  
  # message("Construcing network step by step...")
  # print(au_el)
  
  media_proj <- get_incremental_media_projections(au_el)
  
  n_c <- count_components(media_proj[[n]])
  
  # number of components n_c in each simulation i
  temp_res <- c(i, n_c)
  
  sim_res <- rbind(sim_res, temp_res)
}

message(paste0("Number of connected components in ", NS, " simulations."))
print(sim_res)

```

### Parameterize the probability of attachment

```{r}
build_audience_edgelists <- function(M = 2, N, p = 0.5) {
  all_media <- paste0("M", 1:M)
  all_people <- paste0("N", 1:N)
  
  audience_edgelists <- list()
  audience_edgelist <- NULL
  for(n in all_people) {
    # each person' chooses media at random's choice is no longer random
    media_prob <- c(p, 1-p)
    n_choice <- sample(all_media, 1, replace = TRUE, prob = media_prob)
    
    #network edge between person n and their choice
    n_edge <- c(n, n_choice)
    audience_edgelist <- rbind(audience_edgelist, n_edge)
    
    audience_edgelists[[n]] <- audience_edgelist
  }
  
  return(audience_edgelists)
}

get_incremental_media_projections <- function(audience_edgelists) {
  
  all_people <- length(audience_edgelists)
  # message(all_people)
  media_projection_networks <- list()
  for(i in 1:all_people){
    audience_graph <- graph_from_edgelist(audience_edgelists[[i]], directed = FALSE)
    
    # assign type of node
    V(audience_graph)$type <- substr(V(audience_graph)$name, 1, 1) == "M"
    
    # color node based on type
    V(audience_graph)$color <- ifelse(V(audience_graph)$type, "tomato", "gold")
    
    # change shape of node based on type
    V(audience_graph)$shape <- ifelse(V(audience_graph)$type, "square", "circle") 
    
    # edge color
    E(audience_graph)$edge.color <- "gray80"
    
    # get the audience projection
    media_projection <- bipartite_projection(audience_graph)[[1]]
    
    # store in the list
    media_projection_networks[[i]] <- media_projection
    
    # plot
    # message(i)
    # plot(media_projection)
  }
  
  return(media_projection_networks)
  
}

```

### run the simulation

```{r}
NS <- 100 # number of simulations

set.seed(42)

m = 2
n = 100

curr_p_res <- list()
j <- 1
for(curr_p in seq(0, 1, by = 0.1)) {
  message(paste0("prob: ", curr_p))
  sim_res <- NULL
  for(i in 1:NS) {
    au_el <- build_audience_edgelists(N = n, p = curr_p)
    
    #message("Construcing network step by step...")
    #print(au_el)
    
    media_proj <- get_incremental_media_projections(au_el)
    
    n_c <- count_components(media_proj[[n]])
    
    temp_res <- c(curr_p, i, n_c)
    
    sim_res <- rbind(sim_res, temp_res)
  }
  
  curr_p_res[[j]] <- sim_res
  j <- j+1
}

```

```{r}
sim_res_master <- NULL
for(sim_res in curr_p_res) {
  # sim_res <- data.frame(sim_res, row.names = NULL)
  # names(sim_res) <- c("p", "sim", "nc")
  # sim_res_master <- rbind(sim_res_master, sim_res)
  
  sim_res_master <- sim_res %>% 
    data.frame(row.names = NULL) %>%
    rename(p = X1, sim = X2, nc = X3) %>%
    rbind(sim_res_master)
    
}

print(sim_res_master)
```

```{r}

plot_df <- sim_res_master %>%
  group_by(p, nc) %>%
  tally()

plot_df %>% 
  pull(p) %>%
  unique() %>%
  rep(length(unique(sim_res_master$nc))) %>%
  sort() -> p

plot_df %>%
  pull(nc) %>%
  unique() %>%
  sort() %>%
  rep(length(unique(sim_res_master$p))) -> nc

plot_df <-
  p %>%
  cbind(nc) %>%
  as_tibble() %>%
  rename(p = 1) %>% 
  merge(plot_df, all.x = TRUE) %>%
  mutate(n = replace_na(n, 0))

ggplot(plot_df, aes(x=p, y=n)) +
  geom_line(aes(color=as.factor(nc))) +
  theme_bw() +
  scale_x_continuous(breaks = plot_df$p)
  

```

